version: "3.8"

services:
  db:
    container_name: getnextstarter_db
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres:/data/postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - getnextstarter

networks:
  getnextstarter:
    driver: bridge
